apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azp-agent.fullname" . }}-secret
type: Opaque
stringData:
  AZP_URL: "{{.Values.pipelines.organizationURL}}"
  AZP_TOKEN: "{{.Values.pipelines.personalAccessToken}}"
  AZP_POOL: "{{.Values.pipelines.poolName}}"